import Head from 'next/head'
import Link from 'next/link'
import styles from '../../styles/User.module.scss'

interface IUserProps {

}

export default function User(props: IUserProps) {
  return (
    <div className={styles.container}>
      <Head>
        <title>User App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1>Hello User</h1>
      <Link href="/">Back Home</Link>
    </div>
  )
}

/** Pre-render a page For SSG 场景
 * 编译打包时调用一次，get external data. */
// 只在服务端运行, 不会被打包进bundle. 因此可以在这里访问数据库
// export async function getStaticProps() {
  // Get external data from the file system, API, DB, etc.
//   const data = ... fetch(xxx)

  // The value of the `props` key will be
  //  passed to the `Home` component
//   return {
//     props: ...
//   }
// }


/** Pre-render a page For SSR 场景
 * 每次请求都会调用. context包含所有请求信息 */
// export async function getServerSideProps(context) {
//   return {
//     props: {
      // props for your component
//     },
//   };
// }


/** CSR
 * If you do not need to pre-render the data, choose CSR 的两种场景:
 * - 页面本身是静态的，不需要外部的数据，则不用 SSR\SSR Pre-Render
 * - 想等页面 load 之后，再 fetch 外部的数据 -- useSWR[https://swr.vercel.app/]
 */


/** /posts/[id].js 动态路由 -- /posts/<id> */
// export async function getStaticProps({ params }) {
  // Fetch necessary data for the blog post using params.id
// }
/**
 *  getStaticProps 和 getStaticPaths 只在服务端运行, 只写服务端代码
 */
